use super::*;

fn release(version: &str, prerelease: bool) -> GithubRelease {
    let release = Release {
        version: version.into(),
        notes: "Release notes".into(),
    };
    GithubRelease {
        tag_name: format!("v{version}"),
        draft: false,
        prerelease,
        body: Some(release.notes.clone()),
        assets: vec![
            GithubAsset {
                name: "latest.json".into(),
                browser_download_url: release.manifest_url(),
            },
            GithubAsset {
                name: format!("Starframe_{version}_x64-setup.exe"),
                browser_download_url: release.installer_url(),
            },
        ],
    }
}

#[test]
fn selects_versions_not_dates_and_respects_channel_and_official_assets() {
    let candidates = || {
        vec![
            release("0.7.0-alpha.1", true),
            release("0.6.9", false),
            release("0.6.10", false),
            release("0.5.0", false),
        ]
    };
    assert_eq!(
        select(candidates(), "0.6.0", Channel::Stable)
            .unwrap()
            .unwrap()
            .version,
        "0.6.10"
    );
    assert_eq!(
        select(candidates(), "0.6.0", Channel::Preview)
            .unwrap()
            .unwrap()
            .version,
        "0.7.0-alpha.1"
    );
    assert!(
        select(vec![release("0.6.0", false)], "0.6.0", Channel::Stable)
            .unwrap()
            .is_none()
    );
    assert!(
        select(
            vec![release("0.7.0-alpha.1", false)],
            "0.6.0",
            Channel::Stable
        )
        .unwrap()
        .is_none()
    );
    let mut draft = release("0.9.0", false);
    draft.draft = true;
    let mut foreign = release("0.8.0", false);
    foreign.assets[0].browser_download_url = "https://example.invalid/latest.json".into();
    assert!(
        select(vec![draft, foreign], "0.6.0", Channel::Preview)
            .unwrap()
            .is_none()
    );
    let mut incomplete = release("0.8.0", false);
    incomplete.assets.pop();
    assert!(select(vec![incomplete], "0.6.0", Channel::Preview).is_err());
}

#[test]
fn schedule_merges_manual_checks_and_resume_and_obeys_failure_backoff() {
    assert_eq!(retry_time("120", 100), Some(220));
    assert_eq!(
        retry_time("Wed, 21 Oct 2015 07:28:00 GMT", 100),
        Some(1_445_412_480)
    );
    assert_eq!(retry_time("invalid", 100), None);
    let mut schedule = Schedule::default();
    assert!(!schedule.start(0, false, false, false));
    assert!(schedule.start(1, false, true, false));
    assert!(!schedule.start(2, true, true, false));
    schedule.complete(2, true, None);
    assert!(!schedule.start(301, false, true, false));
    assert!(schedule.start(86400, false, true, false));
    assert!(!schedule.start(86400, true, true, false));
    schedule.complete(86401, false, Some(90000));
    assert!(!schedule.start(89999, true, true, false));
    assert!(schedule.start(90000, false, true, false));
    schedule.complete(90001, false, None);
    assert_eq!(schedule.next, 90601);
    assert!(!schedule.start(90601, true, true, true));
    assert!(schedule.start(90601, true, true, false));
    schedule.complete(90602, true, None);
    assert_eq!(schedule.next, 90902);
}

#[test]
fn retained_notice_and_preferences_survive_restart_and_reject_invalid_cache() {
    let dir = tempfile::tempdir().unwrap();
    let expected = Saved {
        channel: Channel::Stable,
        release: Some(Release {
            version: "0.7.0".into(),
            notes: "<script>plain text only</script>".into(),
        }),
        dismissed: Some("0.7.0".into()),
        last_success: Some(123),
    };
    {
        let mut storage = crate::storage::Storage::open(dir.path()).unwrap();
        storage.save_update_preferences(&expected).unwrap();
        storage.flush().unwrap();
    }
    assert_eq!(
        crate::storage::Storage::open(dir.path())
            .unwrap()
            .update_preferences()
            .unwrap(),
        expected
    );
    assert!(Saved::read(&" ".repeat(70001)).is_err());
    let mut invalid = expected;
    invalid.release.as_mut().unwrap().version = "../bad".into();
    assert!(Saved::read(&serde_json::to_string(&invalid).unwrap()).is_err());
}

#[test]
fn typescript_update_contract_matches_rust() {
    use ts_rs::TS;
    let config = ts_rs::Config::default();
    let content = format!(
        "// Generated by the Rust contract test. Do not edit.\n{}",
        [
            Channel::decl(&config),
            Release::decl(&config),
            Phase::decl(&config),
            View::decl(&config),
            Action::decl(&config)
        ]
        .into_iter()
        .map(|d| format!("export {d}\n"))
        .collect::<String>()
    );
    let path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/lib/generated/updates.ts");
    if std::env::var_os("UPDATE_BINDINGS").is_some() {
        std::fs::write(&path, &content).unwrap();
    }
    assert_eq!(std::fs::read_to_string(path).unwrap(), content);
}
