LangString addOrReinstall ${LANG_ENGLISH} "Repair or reinstall Starframe"
LangString alreadyInstalled ${LANG_ENGLISH} "Starframe is already installed"
LangString alreadyInstalledLong ${LANG_ENGLISH} "Starframe ${VERSION} is installed. Reinstall to restore app files and keep your data, or choose Uninstall to remove Starframe."
LangString appRunning ${LANG_ENGLISH} "Close Starframe normally, then try again."
LangString appRunningOkKill ${LANG_ENGLISH} "Close Starframe normally, then try again."
LangString chooseMaintenanceOption ${LANG_ENGLISH} "Choose what to do with this installation."
LangString choowHowToInstall ${LANG_ENGLISH} "Choose how to replace the installed version."
LangString createDesktop ${LANG_ENGLISH} "Create a desktop shortcut"
LangString dontUninstall ${LANG_ENGLISH} "Replace app files directly (keep my data)"
LangString dontUninstallDowngrade ${LANG_ENGLISH} "Direct replacement is unavailable for an older version"
LangString failedToKillApp ${LANG_ENGLISH} "Starframe is still running. Close it normally, then try again."
LangString installingWebview2 ${LANG_ENGLISH} "Installing Microsoft Edge WebView2..."
LangString newerVersionInstalled ${LANG_ENGLISH} "A newer Starframe version is installed. To install this older version, setup must remove the current app first. Your library and settings will be kept."
LangString older ${LANG_ENGLISH} "older"
LangString olderOrUnknownVersionInstalled ${LANG_ENGLISH} "An $R4 Starframe version is installed. Setup can replace it with ${VERSION}. Your library, collections and settings will be kept."
LangString silentDowngrades ${LANG_ENGLISH} "Silent setup cannot install an older version. Open setup to review the replacement choices.$\n"
LangString unableToUninstall ${LANG_ENGLISH} "Removal did not finish. Resolve the reported problem, then try again."
LangString uninstallApp ${LANG_ENGLISH} "Uninstall Starframe"
LangString uninstallBeforeInstalling ${LANG_ENGLISH} "Remove the current app, then install (keep my data)"
LangString unknown ${LANG_ENGLISH} "unrecognized"
LangString webview2AbortError ${LANG_ENGLISH} "WebView2 installation did not finish. Starframe needs it to display its window. Check your connection, then run setup again."
LangString webview2DownloadError ${LANG_ENGLISH} "WebView2 could not be downloaded. Check your connection and retry. Details: $0"
LangString webview2DownloadSuccess ${LANG_ENGLISH} "WebView2 installer downloaded."
LangString webview2Downloading ${LANG_ENGLISH} "Downloading Microsoft Edge WebView2..."
LangString webview2InstallError ${LANG_ENGLISH} "WebView2 installation failed. Exit code: $1"
LangString webview2InstallSuccess ${LANG_ENGLISH} "Microsoft Edge WebView2 is installed."
LangString deleteAppData ${LANG_ENGLISH} "Delete managed app data"
