use ts_rs::TS;

#[test]
fn generated_management_contract_matches_rust() {
    let config = ts_rs::Config::default();
    let declarations = [
        crate::catalog::Catalog::decl(&config),
        crate::catalog::Mod::decl(&config),
        crate::catalog::Release::decl(&config),
        crate::catalog::CompatibilityProblem::decl(&config),
        crate::catalog::Artifact::decl(&config),
        crate::catalog::Layout::decl(&config),
        crate::storage::Origin::decl(&config),
        crate::storage::ModReference::decl(&config),
        crate::storage::LibraryEntry::decl(&config),
        crate::storage::Collection::decl(&config),
        crate::ordering::Resolution::decl(&config),
        crate::ordering::Adjustment::decl(&config),
        crate::mods::Action::decl(&config),
        crate::mods::View::decl(&config),
        crate::mods::Collision::decl(&config),
        crate::packages::Action::decl(&config),
        crate::packages::Operation::decl(&config),
        crate::packages::Status::decl(&config),
        crate::sharing::Action::decl(&config),
        crate::sharing::Reply::decl(&config),
        crate::sharing::Entry::decl(&config),
        crate::sharing::Status::decl(&config),
        crate::sharing::Import::decl(&config),
    ];
    let content = format!(
        "// Generated by the Rust contract test. Do not edit.\n{}",
        declarations
            .iter()
            .map(|d| format!("export {d}\n"))
            .collect::<String>()
    );
    let path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/lib/generated/management.ts");
    if std::env::var_os("UPDATE_BINDINGS").is_some() {
        std::fs::write(&path, &content).unwrap();
    }
    assert_eq!(std::fs::read_to_string(path).unwrap(), content);
}
