use serde::Serialize;

#[derive(serde::Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum GameAction {
    Discover,
    Setup,
    Launch,
    RemoveRuntime,
    ChooseFolder,
    Select { id: String },
}

#[derive(Clone, Debug, PartialEq, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "snake_case")]
pub enum OperationStatus {
    Running,
    Cancelling,
    Cancelled,
    Completed,
    Failed,
}

#[derive(Clone, Debug, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct Operation {
    pub id: String,
    pub request_id: String,
    pub label: String,
    pub progress: u8,
    pub status: OperationStatus,
    pub message: String,
}

#[derive(Clone, Debug, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct Snapshot {
    pub session_id: String,
    pub revision: String,
    pub app_version: String,
    pub operations: Vec<Operation>,
    pub saved_data: SavedData,
    pub catalog: CatalogStatus,
    #[cfg_attr(test, ts(type = "GameView"))]
    pub game: starframe::game::GameView,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct CatalogStatus {
    pub revision: Option<String>,
    pub release_count: u32,
    pub checking: bool,
    pub last_checked: Option<String>,
    pub last_success: Option<String>,
    pub error: Option<String>,
}

#[derive(Clone, Debug, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(
    tag = "status",
    rename_all = "snake_case",
    rename_all_fields = "camelCase"
)]
pub enum SavedData {
    Loading,
    Ready {
        revision: String,
        library_count: u32,
        collection_count: u32,
        active_collection_name: Option<String>,
    },
    Unavailable {
        message: String,
    },
}

#[derive(Debug, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct CommandError {
    pub code: String,
    pub message: String,
    pub affected_ids: Vec<String>,
    pub recoverable: bool,
}

impl CommandError {
    pub fn new(code: &str, message: &str) -> Self {
        Self {
            code: code.into(),
            message: message.into(),
            affected_ids: vec![],
            recoverable: true,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ts_rs::TS;

    #[test]
    fn typescript_contract_matches_rust() {
        let content = format!(
            "// Generated by the Rust contract test. Do not edit.\nimport type {{ GameView }} from './game';\nexport {}\nexport {}\nexport {}\nexport {}\nexport {}\nexport {}\nexport {}\n",
            OperationStatus::decl(&ts_rs::Config::default()),
            Operation::decl(&ts_rs::Config::default()),
            Snapshot::decl(&ts_rs::Config::default()),
            CommandError::decl(&ts_rs::Config::default()),
            SavedData::decl(&ts_rs::Config::default()),
            GameAction::decl(&ts_rs::Config::default()),
            CatalogStatus::decl(&ts_rs::Config::default())
        );
        let path =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/lib/generated/model.ts");
        if std::env::var_os("UPDATE_BINDINGS").is_some() {
            std::fs::create_dir_all(path.parent().unwrap()).unwrap();
            std::fs::write(&path, &content).unwrap();
        }
        assert_eq!(std::fs::read_to_string(path).unwrap(), content);
    }

    #[test]
    fn revisions_cross_json_without_precision_loss() {
        let snapshot = Snapshot {
            session_id: "test".into(),
            revision: u64::MAX.to_string(),
            app_version: env!("CARGO_PKG_VERSION").into(),
            operations: vec![],
            saved_data: SavedData::Loading,
            catalog: Default::default(),
            game: Default::default(),
        };
        let json = serde_json::to_value(snapshot).unwrap();
        assert_eq!(json["revision"], "18446744073709551615");
        assert_eq!(
            serde_json::to_value(OperationStatus::Cancelling).unwrap(),
            "cancelling"
        );
    }
}
