use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "snake_case")]
pub enum OperationStatus {
    Running,
    Cancelling,
    Cancelled,
    Completed,
    Failed,
}

#[derive(Clone, Debug, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct Operation {
    pub id: String,
    pub request_id: String,
    pub label: String,
    pub progress: u8,
    pub status: OperationStatus,
    pub message: String,
}

#[derive(Clone, Debug, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct Snapshot {
    pub session_id: String,
    pub revision: String,
    pub app_version: String,
    pub operations: Vec<Operation>,
}

#[derive(Debug, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct CommandError {
    pub code: String,
    pub message: String,
    pub affected_ids: Vec<String>,
    pub recoverable: bool,
}

impl CommandError {
    pub fn new(code: &str, message: &str) -> Self {
        Self {
            code: code.into(),
            message: message.into(),
            affected_ids: vec![],
            recoverable: true,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ts_rs::TS;

    #[test]
    fn typescript_contract_matches_rust() {
        let content = format!(
            "// Generated by the Rust contract test. Do not edit.\nexport {}\nexport {}\nexport {}\nexport {}\n",
            OperationStatus::decl(&ts_rs::Config::default()),
            Operation::decl(&ts_rs::Config::default()),
            Snapshot::decl(&ts_rs::Config::default()),
            CommandError::decl(&ts_rs::Config::default())
        );
        let path =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/lib/generated/model.ts");
        if std::env::var_os("UPDATE_BINDINGS").is_some() {
            std::fs::create_dir_all(path.parent().unwrap()).unwrap();
            std::fs::write(&path, &content).unwrap();
        }
        assert_eq!(std::fs::read_to_string(path).unwrap(), content);
    }

    #[test]
    fn revisions_cross_json_without_precision_loss() {
        let snapshot = Snapshot {
            session_id: "test".into(),
            revision: u64::MAX.to_string(),
            app_version: env!("CARGO_PKG_VERSION").into(),
            operations: vec![],
        };
        let json = serde_json::to_value(snapshot).unwrap();
        assert_eq!(json["revision"], "18446744073709551615");
        assert_eq!(
            serde_json::to_value(OperationStatus::Cancelling).unwrap(),
            "cancelling"
        );
    }
}
